source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target “V2EX” do
    pod 'SnapKit', '~> 4.0.0'           # 布局框架 https://github.com/SnapKit/SnapKit，同 Masonry
    pod 'Kingfisher','~>4.2.0'          # 缓存图片 https://github.com/onevcat/Kingfisher，同 SDWebImage
    pod 'Alamofire', '~> 4.5.0'         # 数据请求 https://github.com/Alamofire/Alamofire，同 AFNetworking
    pod 'SwiftyJSON', '~> 3.1.4'        # json 解析 https://github.com/SwiftyJSON/SwiftyJSON
    pod 'SVProgressHUD', '~> 2.1.2'     # 提示功能 https://github.com/SVProgressHUD/SVProgressHUD
    pod 'MJRefresh'                     # 上拉和下拉刷新框架 https://github.com/CoderMJLee/MJRefresh
    
end
